version: "3.1"
services: 
  simpleCA:
    restart: always
    container_name: simple_ca_test
    image: nginx
    ports: 
      - 82:80
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # 配置文件挂载
      - ./nginx/html:/usr/share/nginx/html       # 静态资源根目录挂载
      - ./nginx/log:/var/log/nginx               # 日志文件挂载